<a href="https://colab.research.google.com/github/Sokolkk/DataSciencePython/blob/main/data_science_python6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data science основы с Python #6
 



###Продвинутые операции с Массивами NumPy

###Объединение массивов NumPy

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6, 7, 8, 9, 10])
arrJOIN = np.concatenate((arr, arr1))
print(arrJOIN)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
arr = np.array([[1, 2], [3, 4]])
arr1 = np.array([[5, 6], [7, 8]])
arrJOIN = np.concatenate((arr, arr1), axis=0)

print(arr)
print(arr1)
print(arrJOIN)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


###Объединение .stack

In [22]:
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])
arrJOIN = np.stack((arr, arr1), axis=0)
print(arrJOIN)

[[1 2 3]
 [4 5 6]]


###Объединение .hstack и vstack() и dstack()

 



In [29]:
arr = np.array([1, 2, 3])
arr1 = np.array([4, 5, 6])
arrJOIN = np.vstack((arr, arr1))
arrJOIN2 = np.hstack((arr, arr1))
arrJOIN3 = np.dstack((arr, arr1))

print(arrJOIN)
print(arrJOIN2)
print(arrJOIN3)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


###Разделение массивов NumPy


In [38]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6, 7, 8, 9, 10])
arrJOIN = np.concatenate((arr, arr1))
print(arrJOIN)
arrSPLIT=np.array_split(arrJOIN, 4)
print(arrSPLIT)

[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [43]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6, 7, 8, 9, 10])
arrJOIN = np.concatenate((arr, arr1))
print(arrJOIN)
arrSPLIT=np.split(arrJOIN, 4)
print(arrSPLIT)

[ 1  2  3  4  5  6  7  8  9 10]


ValueError: ignored

In [53]:
arr = np.array([[1, 2], [3, 4]])
arr1 = np.array([[5, 6], [7, 8]])
arrJOIN = np.concatenate((arr, arr1), axis=0)

print(arrJOIN)
arrSPLIT=np.array_split(arrJOIN, 3)
print(arrSPLIT)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [54]:
arr = np.array([[1, 2], [3, 4]])
arr1 = np.array([[5, 6], [7, 8]])
arrJOIN = np.concatenate((arr, arr1), axis=0)

print(arrJOIN)
arrSPLIT=np.array_split(arrJOIN, 3, axis=1)
print(arrSPLIT)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int64)]


###Разделение .hsplit и vsplit и dsplit


In [63]:
arr = np.array([[1, 2], [3, 4]])
arr1 = np.array([[5, 6], [7, 8]])
arrJOIN = np.concatenate((arr, arr1), axis=0)

print(arrJOIN)
arrSPLIT=np.dsplit(arrJOIN)
print(arrSPLIT)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


TypeError: ignored