<a href="https://colab.research.google.com/github/Sokolkk/DataSciencePython/blob/main/data_science_python3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data science основы с Python 
 



###NumPy

In [1]:
!pip install numpy

In [7]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [8]:
type(arr)

numpy.ndarray

#размерность массивов nd

In [20]:
arr1 = np.array(22)
arr2 = np.array((1, 2, 3, 4, 5))
arr3 = np.array(((1, 2, 3), ( 3, 4, 5)))
arr4 = np.array((((1, 2, 3, 4, 5), (1, 2, 3, 4, 5)),  ((1, 2, 3, 4, 5), (1, 2, 3, 4, 5))))
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [21]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

22
[1 2 3 4 5]
[[1 2 3]
 [3 4 5]]
[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [22]:
arr5 = np.array((1, 2, 3, 4, 5), ndmin=6)
print(arr5)
print(arr5.ndim)

[[[[[[1 2 3 4 5]]]]]]
6


Индексирование массивов в NumPy

In [30]:
arr = np.array((1, 2, 3, 4, 5))
print(arr[0:-3])

[1 2]


In [42]:
arr3 = np.array(((1, 2, 3), ( 3, 4, 5)))
print(arr3[1,1])

4


In [49]:
arr4 = np.array((((1, 2, 3, 4, 5), (6, 7, 8, 9, 10)),  ((11, 12, 13, 14, 15), (21, 22, 23, 24, 25))))
print(arr4[0,1,1])

7
