<a href="https://colab.research.google.com/github/Sokolkk/DataSciencePython/blob/main/data_science_python5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Data science основы с Python #5
 



###NumPy: операции с массивами

```
# This is formatted as code
```



###.shape


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


In [7]:
arr = np.array([1, 2, 3], ndmin=4)
print(arr)
print('shape of array :', arr.shape)

[[[[1 2 3]]]]
shape of array : (1, 1, 1, 3)


In [9]:
arr1 = arr.shape + (1, 1)
print(arr1)


(1, 1, 1, 3, 1, 1)


###.reshape

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr1 = arr.reshape(4, 3)
arr2 = arr.reshape(3, 2, 2)


print(arr1)
print(arr1.shape)

print(arr2)
print(arr2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2, 3).base)

[1 2 3 4 5 6]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr1 = arr.reshape(3, 2, -1)
print(arr1)
arr1.reshape(-1) 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###Итерация массивов

In [31]:
arr = np.array([1, 2, 3, 4, 5])
for x in arr:
  print(x)

1
2
3
4
5


In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [42]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [51]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [53]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
